name: Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.18
      uses: actions/setup-go@v2
      with:
        go-version: '1.18.0-beta2'
        stable: 'false'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: go build
      env:
        GOPATH: /home/runner/go

    - name: Run Tests  
      run: go test --race
      env:
        GOPATH: /home/runner/go
